spring:
  application:
    name: MovieRandomizer

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_randomizer_dev
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
