spring:
  application:
    name: MovieRandomizer

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_randomizer_dev
    username: admin
    password: admin
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
